### PR TITLE
Refinement: setting batch_size for different models

### PR DESCRIPTION
**Pull request by riboyuan99**
Since [Google's model](https://github.com/CambioML/uniflow-llm-based-pdf-extraction-text-cleaning-data-clustering/blob/a58216cc85bd673b8a73c68ea9c82fcad45a4f5d/uniflow/op/model/model_config.py#L17), [OpenAI's model](https://github.com/CambioML/uniflow-llm-based-pdf-extraction-text-cleaning-data-clustering/blob/a58216cc85bd673b8a73c68ea9c82fcad45a4f5d/uniflow/op/model/model_config.py#L41), and [Azure OpenAI's model](https://github.com/CambioML/uniflow-llm-based-pdf-extraction-text-cleaning-data-clustering/blob/a58216cc85bd673b8a73c68ea9c82fcad45a4f5d/uniflow/op/model/model_config.py#L54) don't support batching locally, we will instead use `num_thread` to "fake batch" the data.

### CODE REVIEW

**Comment by riboyuan99** [comment]
Will format the code shortly

**Comment by CambioML** [comment]
Please reformat your code to resolve build failure https://github.com/CambioML/uniflow-llm-based-pdf-extraction-text-cleaning-data-clustering/actions/runs/8164445774/job/22319716558?pr=212

**Comment by CambioML** [comment]
Could you please also check all notebook regarding whether you need to make corresponding changes as well as cookbook repo? Get @jojortz to review the cookbook repo.

**Comment by riboyuan99** [comment]
> Could you please also check all notebook regarding whether you need to make corresponding changes as well as cookbook repo? Get @jojortz to review the cookbook repo.

Noted

**Review by CambioML — APPROVED** [review]

**Pull request merged**
